# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 492)
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setGeometry(QtCore.QRect(22, 170, 431, 41))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        self.label_4.setObjectName("label_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.splitter_3)
        self.textEdit_4.setObjectName("textEdit_4")
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setGeometry(QtCore.QRect(30, 230, 411, 41))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_5 = QtWidgets.QLabel(self.splitter_4)
        self.label_5.setObjectName("label_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.splitter_4)
        self.textEdit_5.setObjectName("textEdit_5")
        self.splitter_5 = QtWidgets.QSplitter(Form)
        self.splitter_5.setGeometry(QtCore.QRect(30, 290, 411, 41))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_6 = QtWidgets.QLabel(self.splitter_5)
        self.label_6.setObjectName("label_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.splitter_5)
        self.textEdit_6.setObjectName("textEdit_6")
        self.splitter_6 = QtWidgets.QSplitter(Form)
        self.splitter_6.setGeometry(QtCore.QRect(30, 350, 411, 41))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label_7 = QtWidgets.QLabel(self.splitter_6)
        self.label_7.setObjectName("label_7")
        self.textEdit_7 = QtWidgets.QTextEdit(self.splitter_6)
        self.textEdit_7.setObjectName("textEdit_7")
        self.lab_8 = QtWidgets.QLabel(Form)
        self.lab_8.setGeometry(QtCore.QRect(70, 20, 261, 16))
        self.lab_8.setText("")
        self.lab_8.setObjectName("lab_8")
        self.push = QtWidgets.QPushButton(Form)
        self.push.setGeometry(QtCore.QRect(230, 440, 101, 31))
        self.push.setObjectName("push")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(32, 50, 411, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        self.textEdit.setObjectName("textEdit")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(30, 110, 411, 41))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setObjectName("label_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.splitter_2)
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "молотый/зерновой"))
        self.label_5.setText(_translate("Form", "вкус"))
        self.label_6.setText(_translate("Form", "цена"))
        self.label_7.setText(_translate("Form", "V"))
        self.push.setText(_translate("Form", "добавить"))
        self.label.setText(_translate("Form", "название сорта"))
        self.label_3.setText(_translate("Form", "степень обжарки"))
